name: build_and_test_app

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  run_tests:
    runs-on: ubuntu-latest
    steps:
    - name: ipterziev
      run: ls
    - name: checkout_repo
      uses: actions/checkout@v4
    - name: Use Node.js 20
      uses: actions/setup-node@v3
      with:
        node-version: 20.x
        cache: npm
    - name: install_deps
      run: npm install
    - name: install_playwright
      run: npx playwright install --with-deps
    - name: run_ui_tests
      run: npm run test:ui
  deploy_app:
    needs: run_tests
    runs-on: ubuntu-latest
    steps:
      - name: deploy_to_render
        uses: johnbeybon/render-deploy-action@v0.0.8
        with:
          service-id: ${{secrets.RENDER_SVC_ID}}
          api-key: ${{secrets.RENDER_API_KEY}}
    
